<!--//
**Content Data for Lyrics Library
**Generated by Rhen Gonzaga
//-->

<div id="allData">

 <!-- // Content of All Data// -->
 <form class="ui-filterable">
 <input id="filterBasic-input" data-type="search"> 
 </form>
 
 <ul data-role="listview" data-filter="true" data-input="#filterBasic-input">
  
  <li>Acura</li>
  <li>Audi</li>
  <li>BMW</li>
  <li>Cadillac</li>
  <li>Ferrari</li>
 
 
 </ul>
 
 
 <!-- // End of All Data // -->
</div>

<div id="albumData">
Album loads from content data
</div>